import { Component } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage {

  searchData: string ='';
  employees = [
{"Name":"Orren Imesen","Position":"Associate Professor","Department":"Business Development"},
{"Name":"Bari Springtorp","Position":"Nurse Practicioner","Department":"Marketing"},
{"Name":"Mavis Hurndall","Position":"Payment Adjustment Coordinator","Department":"Business Development"},
{"Name":"Hymie Rydeard","Position":"Recruiter","Department":"Human Resources"},
{"Name":"Hana Shillingford","Position":"Environmental Specialist","Department":"Accounting"},
{"Name":"Bayard Hurne","Position":"Technical Writer","Department":"Product Management"},
{"Name":"Allina Ingledow","Position":"Structural Analysis Engineer","Department":"Training"},
{"Name":"Emelda Haythorn","Position":"Community Outreach Specialist","Department":"Support"},
{"Name":"Boy Crossfeld","Position":"Financial Analyst","Department":"Services"},
{"Name":"Shermie Tison","Position":"Business Systems Development Analyst","Department":"Support"},
{"Name":"Wynn Ledwidge","Position":"Analog Circuit Design manager","Department":"Human Resources"},
{"Name":"Arne Sewley","Position":"Programmer Analyst IV","Department":"Support"},
{"Name":"Michael Ambrosetti","Position":"Analyst Programmer","Department":"Marketing"},
{"Name":"Tammie Treadaway","Position":"Paralegal","Department":"Product Management"},
{"Name":"Janot Selwood","Position":"Environmental Specialist","Department":"Product Management"},
{"Name":"Reena Roth","Position":"Assistant Manager","Department":"Support"},
{"Name":"Rolland Gottelier","Position":"Office Assistant II","Department":"Sales"},
{"Name":"Albertine Stegers","Position":"Design Engineer","Department":"Training"},
{"Name":"Selena Signoret","Position":"Database Administrator IV","Department":"Sales"},
{"Name":"Evangelia Castille","Position":"Tax Accountant","Department":"Product Management"},
{"Name":"Perl Vashchenko","Position":"Marketing Manager","Department":"Sales"},
{"Name":"Erica Duer","Position":"Structural Analysis Engineer","Department":"Human Resources"},
{"Name":"Fara Jurkowski","Position":"Physical Therapy Assistant","Department":"Legal"},
{"Name":"Veronika Mayhew","Position":"Chief Design Engineer","Department":"Engineering"},
{"Name":"Wini Boulds","Position":"Clinical Specialist","Department":"Training"},
{"Name":"Torey Chicken","Position":"Actuary","Department":"Sales"},
{"Name":"Viviene Broker","Position":"Editor","Department":"Business Development"},
{"Name":"Teriann Siebart","Position":"Web Designer I","Department":"Sales"},
{"Name":"Alberik McCauley","Position":"Statistician II","Department":"Support"},
{"Name":"Vivianne Freckelton","Position":"Editor","Department":"Research and Development"},
{"Name":"Oliy Baitey","Position":"Actuary","Department":"Sales"},
{"Name":"Tiertza McFaul","Position":"Clinical Specialist","Department":"Services"},
{"Name":"Thorstein Chatin","Position":"Senior Developer","Department":"Support"},
{"Name":"Daryle Gilbert","Position":"Mechanical Systems Engineer","Department":"Services"},
{"Name":"Belicia Marrington","Position":"Product Engineer","Department":"Legal"},
{"Name":"Zeke Wadelin","Position":"Paralegal","Department":"Human Resources"},
{"Name":"Durward Shadrack","Position":"Sales Associate","Department":"Product Management"},
{"Name":"Elia Hrus","Position":"Web Designer IV","Department":"Services"},
{"Name":"Edmund Blowfield","Position":"VP Product Management","Department":"Business Development"},
{"Name":"Olga Offa","Position":"Software Test Engineer II","Department":"Support"},
{"Name":"Amalee Morling","Position":"Geological Engineer","Department":"Engineering"},
{"Name":"Cloris Law","Position":"Senior Cost Accountant","Department":"Product Management"},
{"Name":"Melonie Bauman","Position":"Software Engineer II","Department":"Sales"},
{"Name":"Corey Samber","Position":"Teacher","Department":"Business Development"},
{"Name":"Alvira Henstridge","Position":"Clinical Specialist","Department":"Accounting"},
{"Name":"Corly Sesser","Position":"Safety Technician II","Department":"Marketing"},
{"Name":"Rock Davsley","Position":"Staff Scientist","Department":"Training"},
{"Name":"Eula Rosenfelt","Position":"Project Manager","Department":"Legal"},
{"Name":"Maryjane Waycot","Position":"Quality Engineer","Department":"Training"},
{"Name":"Amos Hames","Position":"Payment Adjustment Coordinator","Department":"Product Management"},
{"Name":"Fidelio Sallan","Position":"Professor","Department":"Services"},
{"Name":"Garwin Struther","Position":"Community Outreach Specialist","Department":"Research and Development"},
{"Name":"Carlie Goodrum","Position":"Statistician IV","Department":"Marketing"},
{"Name":"Duane Geere","Position":"VP Quality Control","Department":"Accounting"},
{"Name":"Rosy Philipot","Position":"Junior Executive","Department":"Services"},
{"Name":"Carla Willas","Position":"Programmer II","Department":"Engineering"},
{"Name":"Zulema Vidgeon","Position":"Research Associate","Department":"Business Development"},
{"Name":"Andrej Linley","Position":"Geologist II","Department":"Engineering"},
{"Name":"Harrie Liddell","Position":"Project Manager","Department":"Business Development"},
{"Name":"Gusti Portal","Position":"Professor","Department":"Product Management"},
{"Name":"Jake Risson","Position":"Account Representative III","Department":"Training"},
{"Name":"Richmound Damarell","Position":"Senior Editor","Department":"Engineering"},
{"Name":"Tallulah Jehu","Position":"Director of Sales","Department":"Product Management"},
{"Name":"Vernor Maffy","Position":"Administrative Assistant III","Department":"Support"},
{"Name":"Anastassia Airdrie","Position":"Developer I","Department":"Research and Development"},
{"Name":"Barret Zapater","Position":"Executive Secretary","Department":"Human Resources"},
{"Name":"Heath Puckring","Position":"Financial Analyst","Department":"Research and Development"},
{"Name":"Aleda Walwood","Position":"VP Product Management","Department":"Marketing"},
{"Name":"Jan Greenlies","Position":"Librarian","Department":"Research and Development"},
{"Name":"Orlan Swiffin","Position":"Engineer I","Department":"Services"},
{"Name":"Gustavo Grzegorzewicz","Position":"Accountant IV","Department":"Legal"},
{"Name":"Wainwright Corson","Position":"Programmer Analyst I","Department":"Services"},
{"Name":"Moyna Mosconi","Position":"Environmental Specialist","Department":"Accounting"},
{"Name":"Vaclav Graben","Position":"Web Developer III","Department":"Support"},
{"Name":"Joelynn Paske","Position":"Help Desk Technician","Department":"Engineering"},
{"Name":"Sammie Smythe","Position":"Business Systems Development Analyst","Department":"Business Development"},
{"Name":"Reilly Tulk","Position":"Quality Engineer","Department":"Engineering"},
{"Name":"Janeta Helkin","Position":"Analog Circuit Design manager","Department":"Research and Development"},
{"Name":"Brittney Gilvary","Position":"Assistant Media Planner","Department":"Legal"},
{"Name":"Kass Skeete","Position":"Financial Advisor","Department":"Accounting"},
{"Name":"Dyana Wiley","Position":"Budget/Accounting Analyst III","Department":"Human Resources"},
{"Name":"Giovanna Hallowes","Position":"Marketing Assistant","Department":"Product Management"},
{"Name":"Edna Rennocks","Position":"Developer II","Department":"Support"},
{"Name":"Frederik Bennike","Position":"Project Manager","Department":"Support"},
{"Name":"Irita Hitzschke","Position":"Paralegal","Department":"Legal"},
{"Name":"Maiga Klejna","Position":"Web Designer II","Department":"Product Management"},
{"Name":"Law Malan","Position":"Nurse Practicioner","Department":"Product Management"},
{"Name":"Charil Muirden","Position":"Nurse Practicioner","Department":"Support"},
{"Name":"Horace Brogi","Position":"VP Quality Control","Department":"Engineering"},
{"Name":"Alick Fair","Position":"Assistant Manager","Department":"Support"},
{"Name":"Jonell Creak","Position":"Cost Accountant","Department":"Support"},
{"Name":"Ranice O'Bradain","Position":"Accountant II","Department":"Support"},
{"Name":"Jobie McFfaden","Position":"Assistant Manager","Department":"Support"},
{"Name":"Jewell Baus","Position":"Information Systems Manager","Department":"Support"},
{"Name":"Lynne Monnelly","Position":"GIS Technical Architect","Department":"Legal"},
{"Name":"Corliss Pickthorn","Position":"Nurse","Department":"Sales"},
{"Name":"Mercy Mantrup","Position":"Design Engineer","Department":"Services"},
{"Name":"Lura Moscon","Position":"Director of Sales","Department":"Training"},
{"Name":"Talia Nunes Nabarro","Position":"Paralegal","Department":"Legal"},
{"Name":"Gino Stallwood","Position":"Senior Editor","Department":"Business Development"}
  ]

  constructor() {}


}
